export default [
    {
        value: 0,
        label: "",
        spacing: 2,
        labelWidth: 30,
        frontColor: "#BDB2FA",
    },
    { value: 0, frontColor: "#006DFF" },
    {
        value: 0,
        label: "",
        spacing: 2,
        labelWidth: 30,
        frontColor: "#BDB2FA",
    },
    { value: 40, frontColor: "#006DFF" },
    {
        value: 0,
        label: "",
        spacing: 2,
        labelWidth: 30,
        frontColor: "#BDB2FA",
    },
    { value: 0, frontColor: "#006DFF" },
    {
        value: 0,
        label: "",
        spacing: 2,
        labelWidth: 30,
        frontColor: "#BDB2FA",
    },
    { value: 0, frontColor: "#006DFF" },
    {
        value: 0,
        label: "",
        spacing: 2,
        labelWidth: 30,
        frontColor: "#BDB2FA",
    },
    { value: 0, frontColor: "#006DFF" },
    {
        value: 0,
        label: "",
        spacing: 2,
        labelWidth: 30,
        frontColor: "#BDB2FA",
    },
    { value: 0, frontColor: "#006DFF" },
];